server:
  port: 30101

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

spring:
  application:
    name: jec-gateway-base
  zipkin:
    base-url: http://localhost:12000
  sleuth:
    sampler:
      percentage: 1.0
zuul:
  routes:
    user:
      path: /user/**
      serviceId: jec-balance-user
    res:
      path: /res/**
      serviceId: jec-balance-res